backend:
  name: github
  repo: dianafreeman/dianasfreeman
  branch: main

collections:
  - label: Links # Used in the UI
    name: links # Used in routes, e.g., /admin/collections/links
    files:
      - file: "src/content/contentLinks.json"
        label: Home Page Links
        name: links
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
              label: Url,
              name: url,
              widget: string,
              pattern:
                [
                  'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                  'Must be a valid URL',
                ],
            }
          - { label: Icon, name: icon, widget: "select", options: ["bookmark", "checkmark", "handshake", "newwindow", "tiktok", "youtube"] }
          - { label: Date, name: date,   widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: false, format: "LLL", picker_utc: false }
     
      - file: "site/content/navLinks.json"
        label: "Nav Links"
        name: "nav-links"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
              label: Url,
              name: url,
              widget: string,
              pattern:
                [
                  'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                  'Must be a valid URL',
                ],
            }
          - { label: Icon, name: icon, widget: select, options: ["bookmark", "checkmark", "handshake", "newwindow", "tiktok", "youtube"] }
          - { label: Date, name: date,   widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: false, format: "LLL", picker_utc: false }

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
